name: 3. Test unitarias y Reporte de Cobertura 
env:
  DOTNET_VERSION: '8.0'
on: 
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-and-publish-coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configurando la versión de NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies & Run tests with coverage
      run: |
        cd PrimeService
        dotnet restore
        dotnet test --collect:"XPlat Code Coverage"

    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Generate coverage Report
      run: |
        cd PrimeService
        reportgenerator "-reports:./*/*/*/coverage.cobertura.xml" "-targetdir:coverage-report" "-reporttypes:Html"
        # Verificar archivos generados
        ls -la coverage-report/
        # Asegurar que existe index.html
        if [ ! -f "coverage-report/index.html" ] && [ -f "coverage-report/index.htm" ]; then
          cp coverage-report/index.htm coverage-report/index.html
        fi
        
    - name: Deploy coverage report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: PrimeService/coverage-report
        destination_dir: docs 
        keep_files: false
        enable_jekyll: false